name: "Ruby on Rails CI"
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
jobs:
  sqlite:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby 2.7.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.0'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev
          gem update --system
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # - name: Run tests
      #   env: 
      #     DATABASE_URL: sqlite://noticed_test
      #     RAILS_ENV: test
      #   run: |
      #     bin/test

  postgres:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
        ports: ['5432:5432']

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby 2.7.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.0'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsqlite3-dev
          gem update --system
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # - name: Run tests
      #   env: 
      #     DATABASE_URL: postgres://postgres:password@localhost:5432/test
      #     PG_USER: postgres
      #     RAILS_ENV: test
      #   run: |
      #     bin/test
